name: moving_object_disturbance_generator

generator:
  _target_: diffusion_policy.env_runner.disturbance_generator.object_moving_disturbance_generator.ObjectMovingDisturbanceGenerator
  speed: 0.06
  distance_threshold: 0.01